version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 232012
      POSTGRES_DB: data
      
  app:
    image: ellodssa/accesser-1.3:latest
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db   
      
  client:
    image: ellodssa/vaadin-client-1.4:latest
    restart: unless-stopped
    ports:
       - "8080:8080"
    depends_on:
      - app   
    links:
      - app  
      
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    links:
      - es01
    depends_on:
      - es01   
   
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.1
    volumes:
      - ./logstash/config-dir:/usr/share/logstash/config-dir
      - ./logstash/drivers/:/usr/share/logstash/drivers
    command: logstash -f /usr/share/logstash/config-dir/logstash.conf
    links:
      - es01
    depends_on:
      - es01   